baseURL = "https://pomo.one"
languageCode = "en-us"
title = "Pomo"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = 'https://github.com/kevinschoon/pomo'
  homepage_button_text = 'Github'
  homepage_secondary_button_link = "/docs"
  homepage_secondary_button_text = "Read The Docs"
  homepage_intro = 'Pomodoro Command Line Interface'
  homepage_image = '/demo.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Pomodoro Command Line Interface"
    meta_og_title = "Pomo"
    meta_og_type = "website"
    meta_og_url = "https://pomo.one"

  [params.logo]
      mobile = "/tomato_small.png"
      standard  = "/tomato_small.png"
